"""
Response Critic — ARIA's internal evaluator (Phase 3).

This module evaluates draft responses generated by ARIA against the user's
prompt and context. It scores them on accuracy, depth, and honesty.
If the score is too low, it triggers a retry.

Tracks consecutive failures to alert when quality control is degraded.
"""

from __future__ import annotations

from silex.llm.base import SupportsLLM
from silex.models.schemas import CritiqueResponse
from silex.utils.logger import setup_logger

log = setup_logger("silex.critic")

CRITIC_SYSTEM_PROMPT = """You are ARIA's Internal Critic.

Your job is to evaluate a draft response generated by ARIA before the user sees it.
You are strict, objective, and unemotional. You do not rewrite the response; you only score it and provide feedback.

═══════════════════════════════════════════════════════════
SCORING CRITERIA (0.0 to 1.0)
═══════════════════════════════════════════════════════════

1. ACCURACY: Is the information logically sound, internally consistent, and factually correct based on the context?
   - 1.0 = Flawless logic and facts.
   - 0.7 = Minor omissions but generally correct.
   - <0.7 = Hallucinations, logical errors, or contradicts known facts.

2. DEPTH: Does it fully address the core issue? Does it explore nuance or just skim the surface?
   - 1.0 = Nuanced, insightful, goes beyond the obvious.
   - 0.7 = Answers the question adequately but simply.
   - <0.7 = Superficial, misses the point, or gives a generic boilerplate answer.

3. HONESTY: Does the response admit uncertainty where appropriate? Does it avoid overconfidence?
   - 1.0 = Perfectly calibrated confidence. Explicitly states what is unknown.
   - 0.7 = Reasonably calibrated.
   - <0.7 = Arrogant, overly confident about guesses, or hallucinates certainty.

═══════════════════════════════════════════════════════════
EVALUATION RULES
═══════════════════════════════════════════════════════════

- A response is ACCEPTABLE (is_acceptable = true) ONLY IF all three scores are >= 0.7.
- If ANY score is < 0.7, set is_acceptable to false.
- If rejected, your `feedback` must be EXACT, HARSH, and ACTIONABLE. Tell ARIA exactly what she got wrong and what she must fix in Attempt 2. Do not be polite.
- If accepted, `feedback` can be a brief note of approval or minor areas for future improvement.
"""

# Maximum consecutive critic failures before alerting the user
MAX_CONSECUTIVE_FAILURES = 3


class ResponseCritic:
    """Evaluates draft responses for quality and triggers retries if needed."""

    def __init__(self, llm_client: SupportsLLM, model_override: str | None = None):
        self.llm = llm_client
        self.model_override = model_override
        self._consecutive_failures = 0

    async def critique(
        self,
        user_input: str,
        system_context: str,
        draft_response: str,
        draft_reasoning: str,
    ) -> CritiqueResponse:
        """
        Evaluate a draft response using Gemini.
        Returns a structured CritiqueResponse.
        """
        log.debug(f"Critiquing draft response (model: {self.model_override or 'default'})...")

        evaluation_prompt = (
            f"SYSTEM CONTEXT GIVEN TO ARIA:\n{system_context}\n\n"
            f"USER INPUT:\n{user_input}\n\n"
            f"ARIA'S INTERNAL REASONING:\n{draft_reasoning}\n\n"
            f"ARIA'S DRAFT RESPONSE:\n{draft_response}\n\n"
            "Evaluate this draft based on the criteria. Provide scores and feedback."
        )

        try:
            critique = await self.llm.complete_json(
                schema=CritiqueResponse,
                system_prompt=CRITIC_SYSTEM_PROMPT,
                user_input=evaluation_prompt,
                temperature=0.2,
                request_kind="critic",
                model_override=self.model_override,
            )
            
            # Reset failure counter on success
            self._consecutive_failures = 0
            
            log.debug(
                f"Critique complete: Acceptable={critique.is_acceptable} "
                f"(Acc={critique.scores.accuracy:.2f}, "
                f"Dep={critique.scores.depth:.2f}, "
                f"Hon={critique.scores.honesty:.2f})"
            )
            return critique

        except Exception as e:
            self._consecutive_failures += 1
            log.error(
                f"Critic API error ({self._consecutive_failures} consecutive failures): {e}"
            )
            
            # If critic keeps failing, log a prominent warning
            if self._consecutive_failures >= MAX_CONSECUTIVE_FAILURES:
                log.warning(
                    f"⚠ Quality control DEGRADED: Critic has failed "
                    f"{self._consecutive_failures} times in a row. "
                    f"Responses are being accepted without review."
                )
            
            # Fail open to prevent crash loop, but mark it clearly
            return CritiqueResponse(
                scores={"accuracy": 1.0, "depth": 1.0, "honesty": 1.0},
                is_acceptable=True,
                feedback=(
                    f"Critic unavailable (failure #{self._consecutive_failures}). "
                    f"Response accepted without quality review."
                ),
            )
